### PR TITLE
switching to Lit version of table

### PR DESCRIPTION
**Pull request by dlockhart**
This switches things over to use the Lit version of tables and removes the copied styles. There wasn't a demo page for this so I wasn't quite sure how to test it... would someone be able to confirm that this worked or point me at a place I could test this locally? Thanks!

### CODE REVIEW

**Comment by qwangd2l** [comment]
Hey Dave, this repo is in the progress of being moved to a mono repo of content related components: https://github.com/Brightspace/content-components/tree/master/applications/d2l-capture-central
We're not currently working on it or the component itself but will eventually come back to work on this later.

capture-central is set up to be served in BSI for a page in LE as an application with the endpoint `/d2l/wcs/capture-central/<orgId>`
It's also behind a feature flag `capture-central` and behind the Capture tool.

**Comment by dlockhart** [comment]
Ok thanks. I can make a similar change in the `content-components` repo as it also has a copy of these styles.

What should I do with this PR? Can it merge or should I just close it?

**Comment by qwangd2l** [comment]
> Ok thanks. I can make a similar change in the `content-components` repo as it also has a copy of these styles.
> 
> What should I do with this PR? Can it merge or should I just close it?

I think it would be ideal to close this one and merge the change in content-component's capature-central.

**Comment by dlockhart** [comment]
Closing -- will make similar changes in content-component's capture-central.

**Pull request closed without merging**
